---
title: "Tree Transformation"
author: "Callum Bucklow"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
require(dplyr) #data wrangling
require(stringr) #useful string manipulation
require(ggplot2) #data visualisation and plotting
require(ape) #phylogenetic tree plotting and manipulation
require(caper) #phylogenetic generalised least squares (PGLS) regression
require(phytools) #phylogenetic ANOVA
```

```{r Import Data}
#vertebral aspect ratios
cars <- read.csv('Data/vertebral_aspect_ratios.csv')

#import intervertebral distances
ivds <- read.csv('Data/intervertebral_distances.csv')

#import specimen lengths
specimen_lengths <- read.csv('Data/specimen_lengths.csv')

#import all species data
species_data <- read.csv("Data/species_data.csv")
```

```{r Summarise Vertebral Aspect Ratio}
#calculate species averages regardless of caudal or precaudal
cars_species <- cars %>%
  group_by(species_name) %>%
  summarise(
    mean_car_raw = mean(raw_aspect_ratio, na.rm = TRUE),
    mean_car_log = mean(ln_length_ln_width, na.rm = TRUE)
  ) %>%
  mutate(species_name = gsub("_", " ", species_name))
```

```{r Summarise IVDs}
#calculate species averages regardless of caudal or precaudal
ivds <- 
  ivds %>%
  mutate(mean_ivd = (precaudal_intervertebral_distance + caudal_intervertebral_distance)/2)

#calculate species mean              
ivds_species <- 
  ivds %>%
  group_by(species_name) %>%
  summarise(mean_ivd = mean(mean_ivd) )%>%
  mutate(species_name = gsub("_", " ", species_name))
```

```{r Summarise Specimen Lengths}
#calculate average specimen length (we have multiple D macrops A. calli specimens)
species_lengths <- 
  specimen_lengths %>%
  group_by(species_name) %>%
  summarise(ln_standard_length = mean(ln_standard_length)) %>%
  mutate(species_name = gsub("_", " ", species_name))
```

```{r Prepare Species Data}
#append centrum aspect ratios and IVDs to the species data
species_data <-
  species_data %>%
  dplyr::filter(species_name != "Astatotilapia sp. 'Ruaha blue'") %>%
  dplyr::select(-X) %>%
  left_join(ivds_species, by='species_name') %>%
  left_join(cars_species, by='species_name') %>%
  left_join(species_lengths, by='species_name') %>%
  mutate(scaled_IVD = mean_ivd - ln_standard_length) #ratio, both are log transformed so subtract
```


```{r Tree Pruning and Data Subsetting}
#specify tree
tree <- read.tree('Trees/phylogenies_mcgee_2020/phylogeny_mcgee_2020.tre')

#sort out tip labels of the tree
tree$tip.label <- gsub('_', " ", tree$tip.label)

#prune the phylogenetic tree
pruned_tree <- keep.tip(tree, species_data$species_name)

#reorder dataframe so that species order matches order of phylogeny tips
species_data <- 
  species_data %>%
  arrange(match(species_name, pruned_tree$tip.label))
```

```{r}

# Set up 2x2 layout
layout(matrix(1:4, 2, 2))

# Plot trees with smaller tip labels
plot(compute.brlen(pruned_tree, power=1), main=expression(rho==1),
     cex=0.6)   # tip label size
plot(compute.brlen(pruned_tree, power=3), main=expression(rho==3),
     cex=0.6)
plot(compute.brlen(pruned_tree, power=0.5), main=expression(rho==0.5),
     cex=0.6)
plot(compute.brlen(pruned_tree, power=0.25), main=expression(rho==0.25),
     cex=0.6)

layout(1)

```

```{r Transform Pruned Tree}
pruned_tree <- pruned_tree #original tree
pruned_tree_090 <- compute.brlen(pruned_tree, power=0.90) #rho = 0.75
pruned_tree_075 <- compute.brlen(pruned_tree, power=0.75)
pruned_tree_060 <- compute.brlen(pruned_tree, power=0.60)
pruned_tree_045 <- compute.brlen(pruned_tree, power=0.45)
pruned_tree_030 <- compute.brlen(pruned_tree, power=0.30)

#list of transformed trees
trees_list <- list(
  rho_100 = pruned_tree,
  rho_090 = pruned_tree_090,
  rho_075 = pruned_tree_075,
  rho_060 = pruned_tree_060,
  rho_045 = pruned_tree_045,
  rho_030 = pruned_tree_030
)
```

```{r Construct VCV Matrix for Downstream Analysis}
#construct the variance-covariance (VCV) matrix:
#initialize list to store comparative.data objects
vcv_matrices <- list()

#loop over trees and create VCV matrices
for(name in names(trees_list)) {
  vcv_matrices[[name]] <- comparative.data(
    phy = trees_list[[name]],
    data = species_data,
    names.col = species_name,
    vcv = TRUE,
    vcv.dim = 3
  )
}

```

```{r Comparison of PGLS Models}
#empty list
model <- list()

#fit pgls model for total count alone
for(tree in names(trees_list)) {
  model[[tree]] <- pgls(
    mean_car_log ~ total_count,
    data = vcv_matrices[[tree]],
    lambda = "ML"
  )
}

#summarise all models
model_summaries <- lapply(model, summary)
model_summaries

#output lambda and its 95% CI
lambda <- data.frame(
  rho = names(model),
  lambda = sapply(model, function(x) x$param["lambda"]),
  lower95 = sapply(model, function(x) x$param.CI$lambda$ci.val[1]),
  upper95 = sapply(model, function(x) x$param.CI$lambda$ci.val[2])
)
lambda


```

```{r}
#select the model
pgls_model <- model$rho_100

# Grid of lambda values
lambda_seq <- seq(0.001, 0.999, by = 0.01)
loglik_vals <- numeric(length(lambda_seq))

# Compute log-likelihood at each lambda
for(i in seq_along(lambda_seq)) {
  temp_model <- update(pgls_model, lambda = lambda_seq[i])
  loglik_vals[i] <- logLik(temp_model)
}

# Plot the profile
plot(lambda_seq, loglik_vals, type='l', lwd=2,
     xlab=expression(lambda),
     ylab="Log-Likelihood",
     main="Likelihood Profile for Lambda (rho = 1.00)")

# Mark the ML estimate
abline(v = pgls_model$param["lambda"], col="red", lty=2)

```

```{r}

lambda_seq <- seq(0.001, 0.999, by = 0.01)
colors <- rainbow(length(model))  # distinct colors for each tree

plot(NULL, xlim=c(0,1), ylim=c(40, max(sapply(model, function(m) max(logLik(m))))),
     xlab=expression(lambda), ylab="Log-Likelihood", main="Likelihood Profiles for All Trees")

i <- 1
for(tree_name in names(model)) {
  loglik_vals <- numeric(length(lambda_seq))
  for(j in seq_along(lambda_seq)) {
    loglik_vals[j] <- logLik(update(model[[tree_name]], lambda = lambda_seq[j]))
  }
  
  lines(lambda_seq, loglik_vals, col=colors[i], lwd=2)
  abline(v = model[[tree_name]]$param["lambda"], col=colors[i], lty=2)
  i <- i + 1
}

legend("bottomright", legend=names(model), col=colors, lwd=2, lty=1)

```

